export enum NOTIFICATION_ACTIONS {
  SHOW_NOTIFICATION = 'NOTIFICATION/SHOW_NOTIFICATION',
  SET_NOTIFICATION = 'NOTIFICATION/SET_NOTIFICATION',
  CLOSE_NOTIFICATION = 'NOTIFICATION/CLOSE_NOTIFICATION',
}
