export enum AUTH_ACTIONS {
  REQUEST_DATA = 'AUTH/REQUEST_DATA',
  REQUEST_END = 'AUTH/REQUEST_END',
  RECEIVE_DATA = 'AUTH/RECEIVE_DATA',
  REJECT_DATA = 'AUTH/REJECT_DATA',
  CHECK_TOKEN = 'AUTH/CHECK_TOKEN',
}
